# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\User\Mon Drive\Stages\Pleias\RAG_app_mozzilla\ui_forms_v1\chat_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1247, 685)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("/* Central widget: Light grey background */\n"
"#input_frame_2 {\n"
"background-color: rgba(161, 163, 163, 82); \n"
"border: none;  \n"
"border-radius: 10px;   \n"
"}\n"
"#input_textEdit_2{\n"
"background-color: rgba(161, 163, 163, 0); \n"
"border: none;  \n"
"border-radius: 10px;   \n"
"}\n"
"\n"
"QFrame {border:none}\n"
"#upper_frame {border: none}\n"
"#lower_frame {border: none}\n"
"#central_widget {\n"
"    background-color: rgb(211, 211, 211); /* Light grey */\n"
"}\n"
"\n"
"/* Side widgets: White background with slightly rounded borders */\n"
"#side_widget_left, #side_widget_right,  #main_widget, #scrollArea_2  {\n"
"    background-color: rgb(255, 255, 255); /* White */\n"
"    border: 2px solid rgb(255, 255, 255);    /* Greenish border */\n"
"    border-radius: 10px;                  /* Slightly rounded corners */\n"
"}\n"
"\n"
"\n"
"#new_chat_btn{\n"
"    border: 2px solid rgb(211, 211, 211);     /* Greenish border */\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#side_widget_left, #side_widget_right,  #main_widget, #scrollArea_2  {\n"
"    padding: 10px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upper_frame = QtWidgets.QFrame(self.centralwidget)
        self.upper_frame.setMinimumSize(QtCore.QSize(911, 71))
        self.upper_frame.setMaximumSize(QtCore.QSize(16777215, 71))
        self.upper_frame.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0;\n"
"}")
        self.upper_frame.setFrameShape(QtCore.Qt.QFrame::Shape::StyledPanel)
        self.upper_frame.setFrameShadow(QtCore.Qt.QFrame::Shadow::Raised)
        self.upper_frame.setLineWidth(0)
        self.upper_frame.setObjectName("upper_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.upper_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.upper_frame)
        self.pushButton_4.setMinimumSize(QtCore.QSize(75, 0))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.upper_frame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.upper_frame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(678, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.upper_frame)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 0, 4, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.upper_frame)
        self.pushButton_7.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 0, 5, 1, 1)
        self.verticalLayout.addWidget(self.upper_frame)
        self.lower_frame = QtWidgets.QFrame(self.centralwidget)
        self.lower_frame.setMinimumSize(QtCore.QSize(0, 577))
        self.lower_frame.setStyleSheet("")
        self.lower_frame.setFrameShape(QtCore.Qt.QFrame::Shape::StyledPanel)
        self.lower_frame.setFrameShadow(QtCore.Qt.QFrame::Shadow::Raised)
        self.lower_frame.setObjectName("lower_frame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.lower_frame)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.main_widget = QtWidgets.QWidget(self.lower_frame)
        self.main_widget.setStyleSheet("")
        self.main_widget.setObjectName("main_widget")
        self.gridLayout = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.input_frame_2 = QtWidgets.QFrame(self.main_widget)
        self.input_frame_2.setMinimumSize(QtCore.QSize(650, 0))
        self.input_frame_2.setMaximumSize(QtCore.QSize(16777215, 200))
        self.input_frame_2.setStyleSheet("padding: 10px;")
        self.input_frame_2.setFrameShape(QtCore.Qt.QFrame::Shape::StyledPanel)
        self.input_frame_2.setFrameShadow(QtCore.Qt.QFrame::Shadow::Raised)
        self.input_frame_2.setObjectName("input_frame_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.input_frame_2)
        self.gridLayout_8.setContentsMargins(10, 10, 5, 10)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.input_textEdit_2 = QtWidgets.QTextEdit(self.input_frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.input_textEdit_2.setFont(font)
        self.input_textEdit_2.setStyleSheet("border: none;")
        self.input_textEdit_2.setObjectName("input_textEdit_2")
        self.gridLayout_8.addWidget(self.input_textEdit_2, 0, 0, 2, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem1, 0, 1, 1, 1)
        self.send_btn_2 = QtWidgets.QPushButton(self.input_frame_2)
        self.send_btn_2.setMinimumSize(QtCore.QSize(25, 25))
        self.send_btn_2.setMaximumSize(QtCore.QSize(25, 25))
        self.send_btn_2.setStyleSheet("#send_btn {\n"
"border: none;\n"
"padding: 5px;\n"
"border-radius: 5px;\n"
"background:transparent;\n"
"}\n"
"\n"
"#send_btn:hover {\n"
"    background: #ececf1;\n"
"}")
        self.send_btn_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/send.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.send_btn_2.setIcon(icon)
        self.send_btn_2.setIconSize(QtCore.QSize(16, 16))
        self.send_btn_2.setCheckable(False)
        self.send_btn_2.setObjectName("send_btn_2")
        self.gridLayout_8.addWidget(self.send_btn_2, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.input_frame_2, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtCore.Qt.QSizePolicy::Policy::Fixed)
        self.gridLayout.addItem(spacerItem2, 5, 2, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.main_widget)
        self.scrollArea_2.setStyleSheet("border: none;")
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 646, 281))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_3.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_3.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_3.setStyleSheet("background-color: rgb(255, 215, 238);")
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_9.setVerticalSpacing(50)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem3, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout.addWidget(self.scrollArea_2, 0, 1, 1, 2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.main_widget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 3, 1, 1)
        self.horizontalLayout_13.addWidget(self.main_widget)
        self.side_widget_left = QtWidgets.QWidget(self.lower_frame)
        self.side_widget_left.setMinimumSize(QtCore.QSize(400, 0))
        self.side_widget_left.setMaximumSize(QtCore.QSize(250, 16777215))
        self.side_widget_left.setStyleSheet("")
        self.side_widget_left.setObjectName("side_widget_left")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.side_widget_left)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.side_widget_left)
        self.frame_2.setStyleSheet("border: none")
        self.frame_2.setFrameShape(QtCore.Qt.QFrame::Shape::StyledPanel)
        self.frame_2.setFrameShadow(QtCore.Qt.QFrame::Shadow::Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.frame_8 = QtWidgets.QFrame(self.side_widget_left)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_8.setFrameShape(QtCore.Qt.QFrame::Shape::StyledPanel)
        self.frame_8.setFrameShadow(QtCore.Qt.QFrame::Shadow::Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_8)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.open_alex_btn = QtWidgets.QPushButton(self.frame_8)
        self.open_alex_btn.setObjectName("open_alex_btn")
        self.gridLayout_4.addWidget(self.open_alex_btn, 4, 0, 1, 1)
        self.archive_btn = QtWidgets.QPushButton(self.frame_8)
        self.archive_btn.setObjectName("archive_btn")
        self.gridLayout_4.addWidget(self.archive_btn, 5, 0, 1, 1)
        self.upload_pdf_btn = QtWidgets.QPushButton(self.frame_8)
        self.upload_pdf_btn.setObjectName("upload_pdf_btn")
        self.gridLayout_4.addWidget(self.upload_pdf_btn, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 0, 1, 1)
        self.semantic_scholar_btn = QtWidgets.QPushButton(self.frame_8)
        self.semantic_scholar_btn.setObjectName("semantic_scholar_btn")
        self.gridLayout_4.addWidget(self.semantic_scholar_btn, 6, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem5, 7, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.frame_8)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 376, 154))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 2, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.horizontalLayout_13.addWidget(self.side_widget_left)
        self.verticalLayout.addWidget(self.lower_frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1247, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "Logo"))
        self.pushButton_3.setText(_translate("MainWindow", "Library"))
        self.pushButton_2.setText(_translate("MainWindow", "Conversations"))
        self.pushButton_5.setText(_translate("MainWindow", "About"))
        self.pushButton_7.setText(_translate("MainWindow", "Log In"))
        self.input_textEdit_2.setPlaceholderText(_translate("MainWindow", "Type a message"))
        self.pushButton.setText(_translate("MainWindow", "Save to notes"))
        self.label.setText(_translate("MainWindow", "Sources"))
        self.label_2.setText(_translate("MainWindow", "Select the sources on which you want to rely your query"))
        self.label_4.setText(_translate("MainWindow", "External database"))
        self.open_alex_btn.setText(_translate("MainWindow", "Open Alex"))
        self.archive_btn.setText(_translate("MainWindow", "arXiv"))
        self.upload_pdf_btn.setText(_translate("MainWindow", "Upload pdf"))
        self.label_3.setText(_translate("MainWindow", "Internal files"))
        self.semantic_scholar_btn.setText(_translate("MainWindow", "Semantic Scholar"))
import resource_rc
