# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\User\Mon Drive\Stages\Pleias\RAG_app_mozzilla\ui_forms_v1\home_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1172, 845)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("/* Central widget: Light grey background */\n"
"#input_frame_2 {\n"
"background-color: rgba(161, 163, 163, 82); \n"
"border: none;  \n"
"border-radius: 10px;   \n"
"}\n"
"#input_textEdit_2{\n"
"background-color: rgba(161, 163, 163, 0); \n"
"border: none;  \n"
"border-radius: 10px;   \n"
"}\n"
"\n"
"QFrame {border:none}\n"
"#upper_frame {border: none}\n"
"#lower_frame {border: none}\n"
"#central_widget {\n"
"    background-color: rgb(211, 211, 211); /* Light grey */\n"
"}\n"
"\n"
"/* Side widgets: White background with slightly rounded borders */\n"
"#side_widget_left, #side_widget_right,  #main_widget, #scrollArea_2  {\n"
"    background-color: rgb(255, 255, 255); /* White */\n"
"    border: 2px solid rgb(255, 255, 255);    /* Greenish border */\n"
"    border-radius: 10px;                  /* Slightly rounded corners */\n"
"}\n"
"\n"
"\n"
"#new_chat_btn{\n"
"    border: 2px solid rgb(211, 211, 211);     /* Greenish border */\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#side_widget_left, #side_widget_right,  #main_widget, #scrollArea_2  {\n"
"    padding: 10px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.upper_frame = QtWidgets.QFrame(self.centralwidget)
        self.upper_frame.setMinimumSize(QtCore.QSize(911, 71))
        self.upper_frame.setMaximumSize(QtCore.QSize(16777215, 71))
        self.upper_frame.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    padding: 5px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #f0f0f0;\n"
"}")
        self.upper_frame.setFrameShape(QtCore.Qt.QFrame::Shape::StyledPanel)
        self.upper_frame.setFrameShadow(QtCore.Qt.QFrame::Shadow::Raised)
        self.upper_frame.setLineWidth(0)
        self.upper_frame.setObjectName("upper_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.upper_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.upper_frame)
        self.pushButton_4.setMinimumSize(QtCore.QSize(75, 0))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_2.addWidget(self.pushButton_4, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.upper_frame)
        self.pushButton_3.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.upper_frame)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(678, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 0, 3, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.upper_frame)
        self.pushButton_5.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_2.addWidget(self.pushButton_5, 0, 4, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.upper_frame)
        self.pushButton_7.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_2.addWidget(self.pushButton_7, 0, 5, 1, 1)
        self.verticalLayout.addWidget(self.upper_frame)
        self.lower_frame = QtWidgets.QFrame(self.centralwidget)
        self.lower_frame.setMinimumSize(QtCore.QSize(0, 577))
        self.lower_frame.setStyleSheet("")
        self.lower_frame.setFrameShape(QtCore.Qt.QFrame::Shape::StyledPanel)
        self.lower_frame.setFrameShadow(QtCore.Qt.QFrame::Shadow::Raised)
        self.lower_frame.setObjectName("lower_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.lower_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.lower_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("QLabel {\n"
"border: solid 15 px;\n"
"    background-color: rgb(255, 215, 183);\n"
"}")
        self.frame.setFrameShape(QtCore.Qt.QFrame::Shape::StyledPanel)
        self.frame.setFrameShadow(QtCore.Qt.QFrame::Shadow::Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignCenter)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setAlignment(QtCore.Qt.Qt::AlignmentFlag::AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_2.addWidget(self.frame)
        self.pushButton = QtWidgets.QPushButton(self.lower_frame)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 329, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.lower_frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1172, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_4.setText(_translate("MainWindow", "Logo"))
        self.pushButton_3.setText(_translate("MainWindow", "Library"))
        self.pushButton_2.setText(_translate("MainWindow", "Conversations"))
        self.pushButton_5.setText(_translate("MainWindow", "About"))
        self.pushButton_7.setText(_translate("MainWindow", "Log In"))
        self.label.setText(_translate("MainWindow", "Start a reaserch project "))
        self.label_2.setText(_translate("MainWindow", "Start a reaserch project "))
        self.label_3.setText(_translate("MainWindow", "Start a reaserch project "))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
import resource_rc
